### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by tin2tin** [philippe-lavoie/blender-fountain-addon#1]
1.0 installed fine, but I can't install 1.2.1. Blender 2.79b. Win 8. Meaning I can see the files are being placed in the Blender Scripts folder, but it doesn't show up among the add-ons when searching "fountain"?

**Comment by philippe-lavoie** [comment]
There might be a problem when loading the project. Can you start Blender from the command line, it should give you something on the command line to help me diagnose it.

I'll try to do a clean install to see if I can replicate in the meantime.

**Comment by philippe-lavoie** [comment]
It turns out that simply zipping the source code does not create a zip file that Blender likes. I created a simple build script to help me easily create a release zip. Please use that to install the script instead of the source zip.
